git: add a missing reset_copy keyword argument to dirstate.set_tracked()
Since nothing else in hgext/git supports copies yet, the best I can do is avoid
TypeError: set_tracked() got an unexpected keyword argument 'reset_copy'.