parsers: drop one extra argument to PyErr_Format
GCC gave the following warning during `make local`:

mercurial/cext/parsers.c: In function 'dirstate_item_from_v1_data':
mercurial/cext/parsers.c:413:30: warning: too many arguments for format [-Wformat-extra-args]
  413 |                              "unknown state: `%c` (%d, %d, %d)", state, mode,
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

To reproduce, you might need to add the -Wformat-extra-args flag, because it
isn't present for me when building for the default python3. But I can see this
warning while simply building 6.1 with `make PYTHON=python2 clean local`.

I don't think this NULL was useful, because other instances of PyErr_Format()
don't have any NULLs as the final argument, but keep in mind that I don't know
python's C API.